import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getCurrentSession } from "@/actions/auth";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();

  if (user) {
    redirect("/");
  }
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <main className='h-full max-w-7xl mx-auto flex items-center justify-center'>
          {children}
        </main>
      </body>
    </html>
  );
}
